stages:
  prepare:
    cmd: python src/download.py --input data/raw/raw_adult.csv --output data/processed/processed_adult.csv --params params.yaml
    deps:
      - src/download.py
      - data/raw/raw_adult.csv
    params:
      - prepare.iqr_multiplier
      - features.age_bins
    outs:
      - data/processed/processed_adult.csv

  train:
    cmd: python src/train_model.py --input data/processed/processed_adult.csv --output data/models/best_model.txt --params params.yaml --mlflow-dir mlruns
    deps:
      - src/train_model.py
      - data/processed/processed_adult.csv
    params:
      - train.test_size
      - train.cv_folds
    outs:
      - data/models/best_model.txt
    metrics:
      - data/models/metrics.json:
          cache: false
